base/apps/api/urls.py
from django.conf.urls import patterns, url

from .views import ListUsers, TenantList
from .views import GetClusterData, GetFirstrunData, GetClusterServiceData, ClusterServiceAction, \
	GetSystemServiceStatus, SystemServiceAction

from htools.decorators import staff_only

urlpatterns = patterns('',
					url(r'^users/$', staff_only(ListUsers.as_view()), name="api_users"),
					url(r'^cluster/data/$', staff_only(GetClusterData.as_view()), name="get_cluster_data"),
					url(r'^firstrun/data/$', staff_only(GetFirstrunData.as_view()), name="get_firstrun_data"),
					url(r'^service/data/$', staff_only(GetClusterServiceData.as_view()), name="get_cluster_service_data"),
					url(r'^system/service/status/$', staff_only(GetSystemServiceStatus.as_view()), name="get_system_service_status"),


					url(r'^cluster/service/action$', staff_only(ClusterServiceAction.as_view()), name="cluster_service_action"),
					url(r'^system/service/action$', staff_only(SystemServiceAction.as_view()), name="system_service_action"),
					url(r'^tenant/list$', staff_only(TenantList.as_view()), name="api_tenant_id"),
)

base/apps/logger/urls.py
__author__ = 'dgollas'

from django.conf.urls import patterns, url

from .views import LoggerEntries, LoggerClusterServices, LoggerEmailLogEntries, LoggerSnippet, LogsView, LogSnippetView


urlpatterns = patterns('',
				   url(r'^$', LogsView.as_view(), name="cm_logs"),
				   url(r'^snippet/([0-9a-f]{32})/$', LogSnippetView.as_view(), name="cm_logs"),
					url(r'^cluster/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/services$',
						LoggerClusterServices.as_view(), name="api_logger_cluster_services"),
					url(r'^cluster/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/component/([^/]+)$',
						LoggerEntries.as_view(), name="api_logger_cluster_services"),
					url(r'^entries$', LoggerEntries.as_view(), name="api_logger_entries"),
					url(r'^sendmail$', LoggerEmailLogEntries.as_view(), name="api_logger_sendmail"),
					url(r'^snippet/([0-9a-f]{32})/load/$', LoggerSnippet.as_view(), name="api_logger_snippet"),
)

base/apps/tenant/urls.py
from django.conf.urls import patterns, url

from htools.decorators import staff_only

from .views import (
	TenantBackup, TenantsView, TenantMigration, DataTenantStatus, DataTenantBackups, DataTenantTasksInfo,
	DataUpdateTask, SubtaskDetails, TenantClone, TenantDashboard, TenantRestore, TenantSaveGoldenState, DataTenantGS,
	TenantDownloadGoldenState, TenantDeleteGS, ClustersList
)


urlpatterns = patterns(
	'',
	url(r'^clusters/$', staff_only(ClustersList.as_view()), name="clusters_ajax"),

	url(r'^list/$', staff_only(TenantsView.as_view()), name="cm_tenants"),
	url(r'^(?P<tenant_id>\d+)/$', staff_only(TenantDashboard.as_view()), name="tenant_dashboard"),

	url(r'^migration/$', staff_only(TenantMigration.as_view()), name="cm_migration"),
	url(r'^clone/$', staff_only(TenantClone.as_view()), name="cm_clone"),

	url(r'^status_data/$', staff_only(DataTenantStatus.as_view()), name="data_tenant_status"),
	url(r'^tasks_data/$', staff_only(DataTenantTasksInfo.as_view()), name="data_tenant_tasks"),
	url(r'^tasks_data_update/$', staff_only(DataUpdateTask.as_view()), name="data_tenant_tasks_update"),


	url(r'^modal/subtask_data/$', staff_only(SubtaskDetails.as_view()), name="modal_tenant_subtask"),
	url(r'^backup-data/$', staff_only(DataTenantBackups.as_view()), name="tenant_backups"),

	url(r'^backup/$', staff_only(TenantBackup.as_view()), name="cm_tenant_backup"),

	url(r'^restore/$', staff_only(TenantRestore.as_view()), name="cm_tenant_restore"),

	url(r'^golden_state/save/$', staff_only(TenantSaveGoldenState.as_view()), name="tenant_save_gs"),
	url(r'^golden_state/download/$', staff_only(TenantDownloadGoldenState.as_view()), name="tenant_download_gs"),
	url(r'^golden_state/list/$', staff_only(DataTenantGS.as_view()), name="tenant_list_gs"),
	url(r'^golden_state/delete/$', staff_only(TenantDeleteGS.as_view()), name="tenant_delete_gs"),

)

base/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       #url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
                       url(r"^$", RedirectView.as_view(url='/accounts/login/'), name='home'),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^accounts/', include('account.urls')),
                       (r'^api/', include('api.urls')),
                       (r'^cm/', include('cloudmanager.urls')),
                       (r'^cm/tenant/', include('tenant.urls')),
					   (r'^cm/logger/', include('logger.urls')),
                       
                       )
if settings.SERVE_MEDIA:
    urlpatterns += staticfiles_urlpatterns()

base/apps/tenant/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.utils.translation import ugettext_lazy as _
import jsonfield

from cloudmanager.models import Cluster, Node


STARTED = 'ST'
SUCCEEDED = 'SU'
FAILED = 'FA'
CANCELED = 'CA'
TASK_STATE_CHOICES = (
	(STARTED, 'Started'),
	(SUCCEEDED, 'Succeeded'),
	(FAILED, 'Failed'),
	(CANCELED, 'Canceled'),
)


class Tenant(models.Model):
	"""
	A single tenant.
	"""

	tmid = models.IntegerField(_("tenant id"))
	name = models.CharField(_("name"), max_length=50)
	group = models.ManyToManyField(Group)
	cluster = models.ManyToManyField(Cluster)
	attribute = jsonfield.JSONField()

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name = _("tenant")
		verbose_name_plural = _("tenants")
		db_table = "cloudmanager_tenant"


class Task(models.Model):
	"""
	A tenant task.
	Task - Django view task.
	"""
	description = models.TextField(null=True)
	user_id = models.IntegerField(_("user_id"))
	start_dt = models.BigIntegerField()
	end_dt = models.BigIntegerField(null=True)
	status = models.CharField(
		max_length=2,
		choices=TASK_STATE_CHOICES,
		default=STARTED
	)

	class Meta:
		ordering = ['-start_dt', '-id']
		verbose_name = _("tenant_task")
		verbose_name_plural = _("tenant_tasks")
		db_table = "cloudmanager_task"


class Subtask(models.Model):
	"""
	A tenant subtask.
	Subtask is a Celery task. We can have multiple subtasks inside one task - DjangoView.
	"""
	description = models.TextField(null=True)
	start_dt = models.BigIntegerField(null=True)
	end_dt = models.BigIntegerField(null=True)
	job_id = models.CharField(_("job_id"), max_length=50, null=True)
	status = models.CharField(
		max_length=2,
		choices=TASK_STATE_CHOICES,
		default=STARTED
	)
	error_message = models.TextField(null=True)
	task = models.ForeignKey(Task)
	tenant = models.ManyToManyField(Tenant)
	node = models.ManyToManyField(Node)

	class Meta:
		ordering = ['start_dt', 'id']
		verbose_name = _("tenant_subtask")
		verbose_name_plural = _("tenant_subtasks")
		db_table = "cloudmanager_subtask"


class SubtaskStep(models.Model):
	"""
	Subtask steps class: defines an information about the subtask execution process.
	Subtaskstep is a Celery internal execution step(for example: tenant_backup is a 
	substep of migration Celery task. 
	"""
	PENDING = 'PN'
	STARTED = 'ST'
	SUCCEEDED = 'SU'
	FAILED = 'FA'
	SKIPPED = 'SK'
	STEP_STATUS_CHOICES = (
		(PENDING, 'Pending'),
		(STARTED, 'Started'),
		(SUCCEEDED, 'Succeeded'),
		(FAILED, 'Failed'),
		(SKIPPED, 'Skipped'),
	)

	step_identifier = models.CharField(max_length=100, null=True)
	step_num = models.SmallIntegerField()
	start_dt = models.BigIntegerField(null=True)
	end_dt = models.BigIntegerField(null=True)
	status = models.CharField(
		max_length=2,
		choices=STEP_STATUS_CHOICES,
		default=PENDING
	)
	result = models.TextField(null=True)
	comment = models.TextField()
	subtask = models.ForeignKey(Subtask)

	class Meta:
		ordering = ['step_num']
		verbose_name = _("subtask_step")
		verbose_name_plural = _("subtask_steps")
		db_table = "cloudmanager_subtaskstep"


class TenantLock(models.Model):
	"""
	A tenant lock.
	"""
	task = models.ForeignKey(Task, null=True)

	class Meta:
		verbose_name = _("lock")
		verbose_name_plural = _("locks")
		db_table = "cloudmanager_tenantlock"

base/apps/announcements/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

try:
	from notification import models as notification
except ImportError:
	notification = None

from announcements.models import Announcement


class AnnouncementAdminForm(forms.ModelForm):
	"""
	A custom form for the admin of the Announcement model. Has an extra field
	called send_now that when checked will send out the announcement allowing
	the user to decide when that happens.
	"""

	send_now = forms.BooleanField(required=False,
		                          help_text=_("Tick this box to send out this announcement now."))

	class Meta:
		model = Announcement
		exclude = ("creator", "creation_date")

	def save(self, commit=True):
		"""
		Checks the send_now field in the form and when True sends out the
		announcement through notification if present.
		"""

		announcement = super(AnnouncementAdminForm, self).save(commit)
		if self.cleaned_data["send_now"]:
			if notification:
				users = User.objects.all()
				notification.send(users, "announcement", {
					"announcement": announcement,
					}, on_site=False, queue=True)
		return announcement

base/apps/tenant/forms.py
from django import forms
from django.core.exceptions import ValidationError


class BaseTenantForm(forms.Form):
	"""
	Base form class for tenant operation.
	"""

	tenant_id = forms.IntegerField(label='Tenant')
	source_cluster = forms.ChoiceField(label='Source cluster')
	comment = forms.CharField(label='comment', required=False)

	def __init__(self, *args, **kwargs):
		super(BaseTenantForm, self).__init__(*args, **kwargs)
		if (
			self.initial.get('tenant_id', None) and
			self.initial.get('source_cluster', None)):
				self.fields['tenant_id'].value = self.initial['tenant_id']
				self.fields['source_cluster'].choices = self.initial['source_cluster']


class TenantDestinationForm(BaseTenantForm):
	"""
	Extends BaseTenantForm by adding the "destination_cluster" field for
	migration and cloning operations.
	"""

	destination_cluster = forms.ChoiceField(label='Destination cluster')

	def __init__(self, *args, **kwargs):
		super(TenantDestinationForm, self).__init__(*args, **kwargs)
		if self.initial.get('destination_cluster', None):
			self.fields['destination_cluster'].choices = self.initial['destination_cluster']


class BackupTenantForm(BaseTenantForm):
	"""
	Form for tenant's backups
	"""
	pass


class RestoreTenantForm(BaseTenantForm):
	"""
	Form for tenant's restore operation
	"""
	export_id = forms.CharField(label='export_id', required=False)


class MigrateTenantForm(TenantDestinationForm):
	"""
	Tenant migration form
	"""

	MIGRATION_TYPE = (
		(1, 'full tenant migration'),
		(2, 'principals migration'),
	)

	migration_type = forms.ChoiceField(label='Migration type', choices=MIGRATION_TYPE)

	def clean_destination_cluster(self):

		if 'source_cluster' in self.cleaned_data and self.cleaned_data['destination_cluster'] == self.cleaned_data['source_cluster']:
			raise ValidationError('The source cluster cannot be the same as destination cluster')

		return self.cleaned_data['destination_cluster']


class CloneTenantForm (TenantDestinationForm):
	"""
	Tenant clone form.
	"""

	new_tenant_name = forms.CharField(label="New tenant's name", max_length=256)
	new_tenant_id = forms.IntegerField(label="New tenant's id")


class DeleteTBForm(forms.Form):
	"""
	Delete tenant's backup form
	"""
	tenant_id = forms.IntegerField(label='Tenant')
	export_id = forms.IntegerField(label='Backup')

base/apps/announcements/views.py
from django.http import HttpResponseRedirect
from django.views.generic import list_detail
from django.shortcuts import get_object_or_404

from announcements.models import Announcement, current_announcements_for_request

try:
	set
except NameError:
	from sets import Set as set   # Python 2.3 fallback


def announcement_list(request):
	"""
	A basic view that wraps ``django.views.list_detail.object_list`` and
	uses ``current_announcements_for_request`` to get the current
	announcements.
	"""
	queryset = current_announcements_for_request(request)
	return list_detail.object_list(request, **{
		"queryset": queryset,
		"allow_empty": True,
	})


def announcement_hide(request, object_id):
	"""
	Mark this announcement hidden in the session for the user.
	"""
	announcement = get_object_or_404(Announcement, pk=object_id)
	# TODO: perform some basic security checks here to ensure next is not bad
	redirect_to = request.GET.get("next")
	excluded_announcements = request.session.get("excluded_announcements", set())
	excluded_announcements.add(announcement.pk)
	request.session["excluded_announcements"] = excluded_announcements
	return HttpResponseRedirect(redirect_to)

base/apps/api/views.py
import logging

from django.contrib.auth.models import User

from rest_framework.response import Response
from rest_framework.views import APIView
from braces.views import JSONResponseMixin

from tenant.models import Tenant
from saltlib.slib import ClusterData
from .serializers import TenantSerializer


logger = logging.getLogger(__name__)




class ClusterBase(object):
	"""
	View to get cluster object.
	"""

	def getClusters(self, user):
		"""
		Return a list of all users.
		"""
		cluster_ids = []
		groups = user.groups.all()
		for x in groups:
			for y in x.cluster_set.all():
				cluster_ids.append(y.tmid)

		return cluster_ids


class UserList(APIView, JSONResponseMixin):
	"""
	List all users. Demo(Remove later)
	"""

	def get(self, request, format=None, *args, **kwargs):
		return self.render_to_response('')


class TenantList(APIView):
	"""
	Get tenants list.
	"""

	def get(self, request, format=None):
		# FIXME : write dynamic filter (should use many parameters from GET as filter)
		tenant_name = request.GET.get('tenant_name')
		tenant = Tenant.objects.filter(name=tenant_name).all()
		serializer = TenantSerializer(tenant, many=True)
		logger.error(serializer.data)
		return Response(serializer.data)


class ListUsers(APIView, JSONResponseMixin):
	"""
	View to list all users in the system.

	* Requires token authentication.
	* Only admin users are able to access this view.
	"""


	def get(self, request, format=None):
		"""
		Return a list of all users.
		"""
		usernames = [user.username for user in User.objects.all()]
		return self.render_to_response(usernames)


class CntClusterTenent(APIView, JSONResponseMixin):
	"""
	View to list all users in the system.

	* Requires token authentication.
	* Only admin users are able to access this view.
	"""


	def get(self, request, format=None):
		"""
		Return a list of all users.
		"""
		data = self.get_cluster_and_tenant_count(request.user)
		return self.render_to_response(data)


class GetClusterData(APIView, JSONResponseMixin, ClusterBase, ClusterData):
	"""
	View to generate data  for cluter view widgets
	"""


	def get(self, request, format=None):
		"""
		Return a list of all users.
		"""
		cluster_ids = self.getClusters(request.user)
		data = self.getClusterStatus(cluster_ids)

		return self.render_to_response(data)


class GetFirstrunData(APIView, JSONResponseMixin, ClusterBase, ClusterData):
	"""
	Return true/false if cluster is done with firstrun
	"""

	def get(self, request):
		"""
		Return a list of all users.
		"""
		# cluster_ids = self.getClusters(request.user)
		# data = self.get_Firstrun_Status(cluster_ids)
		if request.is_ajax():
			cluster_id = request.GET.get('id', None)
		data = self.get_Firstrun_Status(cluster_id)

		return self.render_to_response(data)


class GetClusterServiceData(APIView, JSONResponseMixin, ClusterBase, ClusterData):
	"""
	View to get cluster services status
	"""

	def get(self, request):
		"""
		Return a dic of service status
		"""

		if request.is_ajax():
			cluster_id = request.GET.get('id', None)
		data = self.get_Cluster_Service_Status(cluster_id)

		return self.render_to_response(data)


class GetSystemServiceStatus(APIView, JSONResponseMixin, ClusterBase, ClusterData):
	"""
	View to get System services status
	"""

	def get(self, request):
		"""
		Return a dic of service status
		"""

		if request.is_ajax():
			cluster_id = request.GET.get('id', None)
		data = self.get_System_Service_Status(cluster_id)

		return self.render_to_response(data)


class ClusterServiceAction(APIView, JSONResponseMixin, ClusterBase, ClusterData):
	"""
	View to get initial status
	"""

	def get(self, request):
		"""
		Return a list of all users.
		"""
		if request.is_ajax():
			cluster_id = request.GET.get('cluster_id', None)
			service = request.GET.get('service', None)
			action = request.GET.get('action', None)
		data = self.cluster_Service_Action(cluster_id, service, action)
		return self.render_to_response(data)


class SystemServiceAction(APIView, JSONResponseMixin, ClusterBase, ClusterData):
	"""
	View to get initial status
	"""

	def get(self, request):
		"""
		Return a list of all users.
		"""
		if request.is_ajax():
			cluster_id = request.GET.get('cluster_id', None)
			service = request.GET.get('service', None)
			action = request.GET.get('action', None)
		data = self.system_Service_Action(cluster_id, service, action)
		return self.render_to_response(data)

base/templates/tenant/base.html
{% extends "theme_base.html" %}

{% block extra_body %}
<div tabindex="-1" class="modal fade" id="ajax-modal"></div>
<div tabindex="-1" id="message-modal" style="display: none;">
{% if messages %}
	    {% for message in messages %}
	    <div>{{ message }}</div>
	    {% endfor %}
{% endif %}
</div>
{% endblock extra_body %}

base/templates/tenant/tenant_backup_info.html
{% load staticfiles %}
{% load tz %}
{% load c_filters %}
{% load c_tags %}
{% if backups %} 
	<div class="row">
		<div class="col-md-12">
			<div id="tenant-backup-{{tenant_id}}-{{cluster_id}}" class="panel-group accordion accordion-alt backups-container" data-tenant="{{tenant_id}}" data-cluster="{{cluster_id}}">
				 {% for backup in backups %}
					<div class="panel">
						<div class="panel-heading"> 
							<a class="accordion-toggle collapsed" data-toggle="collapse" href="#backup-{{backup.export_id}}" data-parent="#tenant-backup-{{tenant_id}}-{{cluster_id}}">
								<div class="accordion-toggle-icon"> 
									<i class="fa fa-minus-square-o"></i> 
									<i class="fa fa-plus-square-o"></i> 
								</div>
								<span class="glyphicons glyphicons-hdd text-blue3"></span>
								{{backup.export_id | epoch_to_datetime:"America/Los_Angeles" }}
							</a>
						</div>
	
						<div id="backup-{{backup.export_id}}" class="panel-collapse collapse">
							<div class="panel-body">
								<div class="row">
									<div class="col-sm-4">
										<div class="row">
											<div class="col-sm-12">
												<b>User: </b><span>{{backup.user_id | user_name}}</span>
											</div>
											<div class="col-sm-12">
												<b>Software version: </b><span>{{backup.cluster_version}}</span>
											</div>
											<div class="col-sm-12">
												<b>Duration: </b><span>{{backup.duration | sec_to_mhd}}</span>
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="row">
											<div class="col-sm-12">
												<b>Start time: </b><span>{{backup.start_timestamp | epoch_to_datetime:"America/Los_Angeles"}}</span>
											</div>
											<div class="col-sm-12">
												<b>End time: </b><span>{{backup.end_timestamp | epoch_to_datetime:"America/Los_Angeles"}}</span>
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="row">
											<div class="col-sm-12">
												<button class="btn btn-green3 pull-right restore-tenant" type="button" data-url="{% url "cm_tenant_restore"%}" data-export-id="{{backup.export_id}}" data-tenant-id="{{tenant_id}}">Restore</button>
											</div>
										</div>
									</div>
								</div>
								<br>
								<div class="row">
									<div class="col-sm-12">
										<table class="table table-hover">
											<thead>
												<tr>
													<th>Storage</th>
													<th>Start time</th>
													<th>End time</th>
													<th>Duration</th>
													<th style="width: 30%">Content</th>
													<th>Tar size</th>
												</tr>
											</thead>
											<tbody>
												{% for storage in backup.meta.storage_info %}
												<tr>
													<td>{{storage.storage_type}}</td>
													<td>{{storage.start_timestamp | epoch_to_datetime:"America/Los_Angeles"}}</td>
													<td>{{storage.end_timestamp | epoch_to_datetime:"America/Los_Angeles"}}</td>
													<td>{{storage.duration | sec_to_mhd}}</td>
													<td>{{storage.exported_data}}</td>
													<td>{{storage.filesize | byte_sizeof_fmt}}</td>
												</tr>
												{% endfor %}
												<tr>
													<td></td>
													<td></td>
													<td></td>
													<td><b>{{backup.summary_duration | sec_to_mhd}}</b></td>
													<td></td>
													<td><b>{{backup.summary_filesize | byte_sizeof_fmt}}</b></td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
								{% if backup.comment %}
								<div class="row">
									<div class="col-sm-12">
										<p><b>Comment: </b>{{backup.comment}}</p>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-12">
										<button class="btn btn-blue3 btn-xs coming-soon" type="button">Edit comment</button>
									</div>
								</div>
								{% else %}
									<div class="row">
									<div class="col-sm-12">
										<button class="btn btn-blue3 btn-xs coming-soon" type="button">Add comment</button>
									</div>
								</div>
								{% endif %}
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" style="margin-bottom: 10px;">   
			{% url "tenant_backups" as pgn_url %}
			{% paginate_ajax backups 5 pgn_url%}
		</div>
	</div>
{% else %}
	<span class="text-danger">There are no tenant's backups for that cluster.</span>
{% endif %}

base/templates/tenant/tenant_task_info.html
{% load staticfiles %}
{% load tz %}
{% load c_filters %}
{% load c_tags %}
{% load tenant_filters %}

{% if tasks %}
	<div class="row">
		<div class="col-md-12">
			<div id="{{tenant_id}}-{{cluster_id}}-acc" class="panel-group accordion accordion-alt tasks-container" data-tenant="{{tenant_id}}" data-cluster="{{cluster_id}}" data-url="{% url "data_tenant_tasks_update" %}" >
				 {% for task in tasks %}
					<div class="panel">
					  <div class="panel-heading"> 
						  <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#{{tenant_id}}-{{cluster_id}}-acc" href="#task-{{tenant_id}}-{{cluster_id}}-{{task.id}}">
						    <div class="accordion-toggle-icon"> 
					            <i class="fa fa-minus-square-o"></i> 
					            <i class="fa fa-plus-square-o"></i> 
					        </div>
					        <span id="task-ico-cont-{{tenant_id}}-{{cluster_id}}">
							    {% if task.status == 'SU' %}
							    <span id="task-{{tenant_id}}-{{cluster_id}}-{{ task.id }}-stat-ico" class="glyphicons glyphicons-ok text-green"></span>
							    {% elif task.status == 'ST' %}
							    <span id="task-{{tenant_id}}-{{cluster_id}}-{{ task.id }}-stat-ico" class="imoon imoon-spinner5 fa-spin cm2-spinner cm2-spinner tm-blue"></span>
							    {% elif task.status == 'CA' %}
							    <span id="task-{{tenant_id}}-{{cluster_id}}-{{ task.id }}-stat-ico" class="glyphicons glyphicons-ban text-red"></span>
							    {% elif task.status == 'FA' %}
					            <span id="task-{{tenant_id}}-{{cluster_id}}-{{ task.id }}-stat-ico" class="glyphicons glyphicons-remove text-red"></span>
					            {% else%}
					            <span id="task-{{tenant_id}}-{{cluster_id}}-{{ task.id }}-stat-ico" class="glyphicons glyphicons-remove text-red"></span>
							    {% endif %}
						    </span>
						    {{task.description}}
						  </a>  
					   </div>
						<div id="task-{{tenant_id}}-{{cluster_id}}-{{task.id}}" class="panel-collapse collapse">
							<div class="panel-body">
								<b>Owner: </b><span id="task-{{tenant_id}}-{{cluster_id}}-{{task.id}}-owner">{{task.user_id | user_name}}</span><br>
								<b>Status: </b><span id="task-{{tenant_id}}-{{cluster_id}}-{{task.id}}-status">{{task.status | task_status}}</span><br>
								<b>Start time: </b><span id="task-{{tenant_id}}-{{cluster_id}}-{{task.id}}-start-time">{{ task.start_dt | epoch_to_datetime:"America/Los_Angeles" }}</span><br>
								<b>End time: </b><span id="task-{{tenant_id}}-{{cluster_id}}-{{task.id}}-end-time">{{ task.end_dt | epoch_to_datetime:"America/Los_Angeles"}}</span><br><br>
								<table class="table table-hover">
									<thead>
										<tr>
										    <th>Start time</th>
										    <th>End time</th>
										    <th>Status</th>
										    <th>Description</th>
										</tr>
									</thead>
								    <tbody>
									    {% for subtask in task.subtask_set.all %}
									    <tr class="alert-link subtask-info cur-pointer" data-toggle="modal" data-url="{% url "modal_tenant_subtask" %}" data-jid="{{subtask.job_id}}" href="javascript:void(0)">
										    <td id="subtask-{{tenant_id}}-{{cluster_id}}-{{subtask.job_id}}-start-time">{{ subtask.start_dt | epoch_to_datetime:"America/Los_Angeles" }}</td>
										    <td id="subtask-{{tenant_id}}-{{cluster_id}}-{{subtask.job_id}}-end-time">{{ subtask.end_dt | epoch_to_datetime:"America/Los_Angeles" }}</td>
										    <td id="subtask-{{tenant_id}}-{{cluster_id}}-{{subtask.job_id}}-status">{{ subtask.status | task_status }}</td>
										    <td id="subtask-{{tenant_id}}-{{cluster_id}}-{{subtask.job_id}}-description">{{ subtask.description }}</td>
									    </tr>
									    {% endfor %}
								    </tbody>
								</table>
							</div>
					  </div>
					</div>
					{% endfor %}   
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12" style="margin-bottom: 10px;">   
			{% url "data_tenant_tasks" as pgn_url %}
			{% paginate_ajax tasks 5 pgn_url%}
		</div>
	</div>
{% else %}
	<span>There are no tenant's tasks on that cluster.</span>
{% endif %}