base/apps/api/urls.py
from django.conf.urls import patterns, url

from .views import ListUsers, TenantList
from .views import GetClusterData, GetFirstrunData, GetClusterServiceData, ClusterServiceAction, \
	GetSystemServiceStatus, SystemServiceAction

from htools.decorators import staff_only

urlpatterns = patterns('',
					url(r'^users/$', staff_only(ListUsers.as_view()), name="api_users"),
					url(r'^cluster/data/$', staff_only(GetClusterData.as_view()), name="get_cluster_data"),
					url(r'^firstrun/data/$', staff_only(GetFirstrunData.as_view()), name="get_firstrun_data"),
					url(r'^service/data/$', staff_only(GetClusterServiceData.as_view()), name="get_cluster_service_data"),
					url(r'^system/service/status/$', staff_only(GetSystemServiceStatus.as_view()), name="get_system_service_status"),


					url(r'^cluster/service/action$', staff_only(ClusterServiceAction.as_view()), name="cluster_service_action"),
					url(r'^system/service/action$', staff_only(SystemServiceAction.as_view()), name="system_service_action"),
					url(r'^tenant/list$', staff_only(TenantList.as_view()), name="api_tenant_id"),
)

base/apps/logger/urls.py
__author__ = 'dgollas'

from django.conf.urls import patterns, url

from .views import LoggerEntries, LoggerClusterServices, LoggerEmailLogEntries, LoggerSnippet, LogsView, LogSnippetView


urlpatterns = patterns('',
				   url(r'^$', LogsView.as_view(), name="cm_logs"),
				   url(r'^snippet/([0-9a-f]{32})/$', LogSnippetView.as_view(), name="cm_logs"),
					url(r'^cluster/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/services$',
						LoggerClusterServices.as_view(), name="api_logger_cluster_services"),
					url(r'^cluster/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/component/([^/]+)$',
						LoggerEntries.as_view(), name="api_logger_cluster_services"),
					url(r'^entries$', LoggerEntries.as_view(), name="api_logger_entries"),
					url(r'^sendmail$', LoggerEmailLogEntries.as_view(), name="api_logger_sendmail"),
					url(r'^snippet/([0-9a-f]{32})/load/$', LoggerSnippet.as_view(), name="api_logger_snippet"),
)

base/apps/tenant/urls.py
from django.conf.urls import patterns, url

from htools.decorators import staff_only

from .views import (
	TenantBackup, TenantsView, TenantMigration, DataTenantStatus, DataTenantBackups, DataTenantTasksInfo,
	DataUpdateTask, SubtaskDetails, TenantClone, TenantDashboard, TenantRestore, TenantSaveGoldenState, DataTenantGS,
	TenantDownloadGoldenState, TenantDeleteGS, ClustersList
)


urlpatterns = patterns(
	'',
	url(r'^clusters/$', staff_only(ClustersList.as_view()), name="clusters_ajax"),

	url(r'^list/$', staff_only(TenantsView.as_view()), name="cm_tenants"),
	url(r'^(?P<tenant_id>\d+)/$', staff_only(TenantDashboard.as_view()), name="tenant_dashboard"),

	url(r'^migration/$', staff_only(TenantMigration.as_view()), name="cm_migration"),
	url(r'^clone/$', staff_only(TenantClone.as_view()), name="cm_clone"),

	url(r'^status_data/$', staff_only(DataTenantStatus.as_view()), name="data_tenant_status"),
	url(r'^tasks_data/$', staff_only(DataTenantTasksInfo.as_view()), name="data_tenant_tasks"),
	url(r'^tasks_data_update/$', staff_only(DataUpdateTask.as_view()), name="data_tenant_tasks_update"),


	url(r'^modal/subtask_data/$', staff_only(SubtaskDetails.as_view()), name="modal_tenant_subtask"),
	url(r'^backup-data/$', staff_only(DataTenantBackups.as_view()), name="tenant_backups"),

	url(r'^backup/$', staff_only(TenantBackup.as_view()), name="cm_tenant_backup"),

	url(r'^restore/$', staff_only(TenantRestore.as_view()), name="cm_tenant_restore"),

	url(r'^golden_state/save/$', staff_only(TenantSaveGoldenState.as_view()), name="tenant_save_gs"),
	url(r'^golden_state/download/$', staff_only(TenantDownloadGoldenState.as_view()), name="tenant_download_gs"),
	url(r'^golden_state/list/$', staff_only(DataTenantGS.as_view()), name="tenant_list_gs"),
	url(r'^golden_state/delete/$', staff_only(TenantDeleteGS.as_view()), name="tenant_delete_gs"),

)

base/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       #url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
                       url(r"^$", RedirectView.as_view(url='/accounts/login/'), name='home'),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^accounts/', include('account.urls')),
                       (r'^api/', include('api.urls')),
                       (r'^cm/', include('cloudmanager.urls')),
                       (r'^cm/tenant/', include('tenant.urls')),
					   (r'^cm/logger/', include('logger.urls')),
                       
                       )
if settings.SERVE_MEDIA:
    urlpatterns += staticfiles_urlpatterns()

base/apps/account/models.py
import datetime
import operator
import urllib

from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db import models, transaction
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.utils import timezone, translation
from django.utils.translation import gettext_lazy as _

from django.contrib.auth.models import User, AnonymousUser
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site

import pytz

from account import signals
from account.conf import settings
from account.fields import TimeZoneField
from account.managers import EmailAddressManager, EmailConfirmationManager, \
	AllowedObjectPermissionManager
from account.signals import signup_code_sent, signup_code_used
from account.utils import random_token
from cloudmanager.models import Cluster, Node
from tenant.models import Tenant


class Account(models.Model):

	user = models.OneToOneField(User, related_name="account", verbose_name=_("user"))
	timezone = TimeZoneField(_("timezone"))
	language = models.CharField(_("language"),
								max_length=10,
								choices=settings.ACCOUNT_LANGUAGES,
								default=settings.LANGUAGE_CODE
	)

	@classmethod
	def for_request(cls, request):
		if request.user.is_authenticated():
			try:
				account = Account._default_manager.get(user=request.user)
			except Account.DoesNotExist:
				account = AnonymousAccount(request)
		else:
			account = AnonymousAccount(request)
		return account

	@classmethod
	def create(cls, request=None, **kwargs):
		create_email = kwargs.pop("create_email", True)
		confirm_email = kwargs.pop("confirm_email", None)
		account = cls(**kwargs)
		if "language" not in kwargs:
			if request is None:
				account.language = settings.LANGUAGE_CODE
			else:
				account.language = translation.get_language_from_request(request, check_path=True)
		account.save()
		if create_email and account.user.email:
			kwargs = {"primary": True}
			if confirm_email is not None:
				kwargs["confirm"] = confirm_email
			EmailAddress.objects.add_email(account.user, account.user.email, **kwargs)
		return account

	def __unicode__(self):
		return self.user.username

	def now(self):
		"""
		Returns a timezone aware datetime localized to the account's timezone.
		"""
		now = datetime.datetime.utcnow().replace(tzinfo=pytz.timezone("UTC"))
		timezone = settings.TIME_ZONE if not self.timezone else self.timezone
		return now.astimezone(pytz.timezone(timezone))

	def localtime(self, value):
		"""
		Given a datetime object as value convert it to the timezone of
		the account.
		"""
		timezone = settings.TIME_ZONE if not self.timezone else self.timezone
		if value.tzinfo is None:
			value = pytz.timezone(settings.TIME_ZONE).localize(value)
		return value.astimezone(pytz.timezone(timezone))


@receiver(post_save, sender=User, dispatch_uid="user-account-creation-signal")
def user_post_save(sender, **kwargs):
	"""
	After User.save is called we check to see if it was a created user. If so,
	we check if the User object wants account creation. If all passes we
	create an Account object.

	We only run on user creation to avoid having to check for existence on
	each call to User.save.
	"""
	user, created = kwargs["instance"], kwargs["created"]
	disabled = getattr(user, "_disable_account_creation", not settings.ACCOUNT_CREATE_ON_SAVE)
	if created and not disabled:
		Account.create(user=user)


class AnonymousAccount(object):

	def __init__(self, request=None):
		self.user = AnonymousUser()
		self.timezone = settings.TIME_ZONE
		if request is None:
			self.language = settings.LANGUAGE_CODE
		else:
			self.language = translation.get_language_from_request(request, check_path=True)

	def __unicode__(self):
		return "AnonymousAccount"


class SignupCode(models.Model):

	class AlreadyExists(Exception):
		pass

	class InvalidCode(Exception):
		pass

	code = models.CharField(max_length=64, unique=True)
	max_uses = models.PositiveIntegerField(default=0)
	expiry = models.DateTimeField(null=True, blank=True)
	inviter = models.ForeignKey(User, null=True, blank=True)
	email = models.EmailField(blank=True)
	notes = models.TextField(blank=True)
	sent = models.DateTimeField(null=True, blank=True)
	created = models.DateTimeField(default=timezone.now, editable=False)
	use_count = models.PositiveIntegerField(editable=False, default=0)

	def __unicode__(self):
		if self.email:
			return u"%s [%s]" % (self.email, self.code)
		else:
			return self.code

	@classmethod
	def exists(cls, code=None, email=None):
		checks = []
		if code:
			checks.append(Q(code=code))
		if email:
			checks.append(Q(email=code))
		return cls._default_manager.filter(reduce(operator.or_, checks)).exists()

	@classmethod
	def create(cls, **kwargs):
		email, code = kwargs.get("email"), kwargs.get("code")
		if kwargs.get("check_exists", True) and cls.exists(code=code, email=email):
			raise cls.AlreadyExists()
		expiry = timezone.now() + datetime.timedelta(hours=kwargs.get("expiry", 24))
		if not code:
			code = random_token([email]) if email else random_token()
		params = {
			"code": code,
			"max_uses": kwargs.get("max_uses", 0),
			"expiry": expiry,
			"inviter": kwargs.get("inviter"),
			"notes": kwargs.get("notes", "")
		}
		if email:
			params["email"] = email
		return cls(**params)

	@classmethod
	def check(cls, code):
		try:
			signup_code = cls._default_manager.get(code=code)
		except cls.DoesNotExist:
			raise cls.InvalidCode()
		else:
			if signup_code.max_uses and signup_code.max_uses <= signup_code.use_count:
				raise cls.InvalidCode()
			else:
				if signup_code.expiry and timezone.now() > signup_code.expiry:
					raise cls.InvalidCode()
				else:
					return signup_code

	def calculate_use_count(self):
		self.use_count = self.signupcoderesult_set.count()
		self.save()

	def use(self, user):
		"""
		Add a SignupCode result attached to the given user.
		"""
		result = SignupCodeResult()
		result.signup_code = self
		result.user = user
		result.save()
		signup_code_used.send(sender=result.__class__, signup_code_result=result)

	def send(self, **kwargs):
		protocol = getattr(settings, "DEFAULT_HTTP_PROTOCOL", "http")
		current_site = kwargs["site"] if "site" in kwargs else Site.objects.get_current()
		signup_url = u"%s://%s%s?%s" % (
			protocol,
			unicode(current_site.domain),
			reverse("account_signup"),
			urllib.urlencode({"code": self.code})
		)
		ctx = {
			"signup_code": self,
			"current_site": current_site,
			"signup_url": signup_url,
			}
		subject = render_to_string("account/email/invite_user_subject.txt", ctx)
		message = render_to_string("account/email/invite_user.txt", ctx)
		send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email])
		self.sent = timezone.now()
		self.save()
		signup_code_sent.send(sender=SignupCode, signup_code=self)


class SignupCodeResult(models.Model):

	signup_code = models.ForeignKey(SignupCode)
	user = models.ForeignKey(User)
	timestamp = models.DateTimeField(default=datetime.datetime.now)

	def save(self, **kwargs):
		super(SignupCodeResult, self).save(**kwargs)
		self.signup_code.calculate_use_count()


class EmailAddress(models.Model):

	user = models.ForeignKey(User)
	email = models.EmailField(unique=settings.ACCOUNT_EMAIL_UNIQUE)
	verified = models.BooleanField(default=False)
	primary = models.BooleanField(default=False)

	objects = EmailAddressManager()

	class Meta:
		verbose_name = _("email address")
		verbose_name_plural = _("email addresses")
		if not settings.ACCOUNT_EMAIL_UNIQUE:
			unique_together = [("user", "email")]

	def __unicode__(self):
		return u"%s (%s)" % (self.email, self.user)

	def set_as_primary(self, conditional=False):
		old_primary = EmailAddress.objects.get_primary(self.user)
		if old_primary:
			if conditional:
				return False
			old_primary.primary = False
			old_primary.save()
		self.primary = True
		self.save()
		self.user.email = self.email
		self.user.save()
		return True

	def send_confirmation(self):
		confirmation = EmailConfirmation.create(self)
		confirmation.send()
		return confirmation

	def change(self, new_email, confirm=True):
		"""
		Given a new email address, change self and re-confirm.
		"""
		with transaction.commit_on_success():
			self.user.email = new_email
			self.user.save()
			self.email = new_email
			self.verified = False
			self.save()
			if confirm:
				self.send_confirmation()


class EmailConfirmation(models.Model):

	email_address = models.ForeignKey(EmailAddress)
	created = models.DateTimeField(default=timezone.now())
	sent = models.DateTimeField(null=True)
	key = models.CharField(max_length=64, unique=True)

	objects = EmailConfirmationManager()

	class Meta:
		verbose_name = _("email confirmation")
		verbose_name_plural = _("email confirmations")

	def __unicode__(self):
		return u"confirmation for %s" % self.email_address

	@classmethod
	def create(cls, email_address):
		key = random_token([email_address.email])
		return cls._default_manager.create(email_address=email_address, key=key)

	def key_expired(self):
		expiration_date = self.sent + datetime.timedelta(days=settings.ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS)
		return expiration_date <= timezone.now()
	key_expired.boolean = True

	def confirm(self):
		if not self.key_expired() and not self.email_address.verified:
			email_address = self.email_address
			email_address.verified = True
			email_address.set_as_primary(conditional=True)
			email_address.save()
			signals.email_confirmed.send(sender=self.__class__, email_address=email_address)
			return email_address

	def send(self, **kwargs):
		current_site = kwargs["site"] if "site" in kwargs else Site.objects.get_current()
		protocol = getattr(settings, "DEFAULT_HTTP_PROTOCOL", "http")
		activate_url = u"%s://%s%s" % (
			protocol,

base/apps/announcements/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

try:
	from notification import models as notification
except ImportError:
	notification = None

from announcements.models import Announcement


class AnnouncementAdminForm(forms.ModelForm):
	"""
	A custom form for the admin of the Announcement model. Has an extra field
	called send_now that when checked will send out the announcement allowing
	the user to decide when that happens.
	"""

	send_now = forms.BooleanField(required=False,
		                          help_text=_("Tick this box to send out this announcement now."))

	class Meta:
		model = Announcement
		exclude = ("creator", "creation_date")

	def save(self, commit=True):
		"""
		Checks the send_now field in the form and when True sends out the
		announcement through notification if present.
		"""

		announcement = super(AnnouncementAdminForm, self).save(commit)
		if self.cleaned_data["send_now"]:
			if notification:
				users = User.objects.all()
				notification.send(users, "announcement", {
					"announcement": announcement,
					}, on_site=False, queue=True)
		return announcement

base/pkgs/braces/forms.py
class UserKwargModelFormMixin(object):
	"""
	Generic model form mixin for popping user out of the kwargs and
	attaching it to the instance.

	This mixin must precede forms.ModelForm/forms.Form. The form is not
	expecting these kwargs to be passed in, so they must be poppped off before
	anything else is done.
	"""
	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop("user", None)  # Pop the user off the
												# passed in kwargs.
		super(UserKwargModelFormMixin, self).__init__(*args, **kwargs)

base/apps/announcements/views.py
from django.http import HttpResponseRedirect
from django.views.generic import list_detail
from django.shortcuts import get_object_or_404

from announcements.models import Announcement, current_announcements_for_request

try:
	set
except NameError:
	from sets import Set as set   # Python 2.3 fallback


def announcement_list(request):
	"""
	A basic view that wraps ``django.views.list_detail.object_list`` and
	uses ``current_announcements_for_request`` to get the current
	announcements.
	"""
	queryset = current_announcements_for_request(request)
	return list_detail.object_list(request, **{
		"queryset": queryset,
		"allow_empty": True,
	})


def announcement_hide(request, object_id):
	"""
	Mark this announcement hidden in the session for the user.
	"""
	announcement = get_object_or_404(Announcement, pk=object_id)
	# TODO: perform some basic security checks here to ensure next is not bad
	redirect_to = request.GET.get("next")
	excluded_announcements = request.session.get("excluded_announcements", set())
	excluded_announcements.add(announcement.pk)
	request.session["excluded_announcements"] = excluded_announcements
	return HttpResponseRedirect(redirect_to)

base/templates/profiles/company_audit.html
{% extends "sd_admin/base.html" %}

{% load i18n %}
{% load humanize %}

{% block head_title %}{% blocktrans %}Company Audit List{% endblocktrans %}{% endblock %}

{% block nav_title %}Show: Company Audit{% endblock nav_title %}

{% block extra_javascript %}

<link href="{{MEDIA_URL}}css/themes/skydrea/jquery-ui-1.7.2.custom.css" rel="stylesheet" type="text/css" />
<script src="{{MEDIA_URL}}js/i18n/grid.locale-en.js" type="text/javascript"></script> 
<script src="{{MEDIA_URL}}js/jquery.jqGrid.min.js" type="text/javascript"></script> 
<link href="{{MEDIA_URL}}css/ui.jqgrid.css" rel="stylesheet" type="text/css" />
<script src="{{MEDIA_URL}}js/jquery-ui-1.7.2.custom.min.js" type="text/javascript"></script>

<!-- Additional IE/Win specific style sheet (Conditional Comments) -->
<!--[if lte IE 7]>
<link rel="stylesheet" href="{{MEDIA_URL}}css/jquery.tabs-ie.css" type="text/css" media="projection, screen">
<![endif]-->
{% endblock extra_javascript %}



{% block content %}
	<div style="clear:both; padding-top:7px;">
		<table id="list_cadt" class="scroll" cellpadding="0" cellspacing="0"></table>
		<div id="pager_cadt" class="scroll" style="text-align:center;"></div>
		<script src="{{MEDIA_URL}}js/cadt.js" type="text/javascript"> </script>
	</div>
{% endblock content %} 

base/templates/profiles/company_edit.html
{% extends "sd_admin/base.html" %}

{% load i18n %}
{% load uni_form_tags %}

{% block head_title %}{% blocktrans %}Update Company{% endblocktrans %}{% endblock %}

{% block nav_title %}Show: Update Company{% endblock nav_title %}


{% block extra_javascript %}
	<link type="text/css" rel="stylesheet" href="{{ MEDIA_URL }}css/themes/skydrea/jquery-ui-1.7.2.custom.css" />
	<link type="text/css" href="{{ MEDIA_URL }}css/ui.multiselect.css" rel="stylesheet" />
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/common.css" type="text/css" />
	<!--<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.3.2.min.js"></script>-->
	<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-ui-1.7.1.custom.min.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}js/plugins/localisation/jquery.localisation-min.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}js/plugins/tmpl/jquery.tmpl.1.1.1.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}js/plugins/blockUI/jquery.blockUI.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}js/ui.multiselect.js"></script>
	<script type="text/javascript">		
	$(document).ready(function(){
			$("#id_sub_aws_services").multiselect();
	});
	</script>
	<style type="text/css">
	
	#id_sub_aws_services{
			width:890px;
			height:500px;
		}
	#id_location{
		height:100px;
		width:300px;
	}
	#company_info fieldset{
		//min-height:320px;
	}
	</style>
{% endblock extra_javascript %}

{% block content %}
<form class="uniForm" method="POST" action="{% url "company_edit" %}" style="width:940px">{% csrf_token %}
	<fieldset id="company_info" style="float:left;width:935px">
		<legend>{% trans "Company Info" %}</legend>
		<div style="width:49%;float:left;">
		<div class="f_i_e">{{ form.name.errors }}</div>
		<div class="f_i_t">{{ form.name.label_tag }}</div>
		<div class="f_i_i">{{ form.name }}</div>
		<div class="f_i_e">{{ form.location.errors }}</div>
		<div class="f_i_t">{{ form.location.label_tag }}</div>
		<div class="f_i_i">{{ form.location }}</div>
		<div class="f_i_e">{{ form.contact_user.errors }}</div>
		<div class="f_i_t">{{ form.contact_user.label_tag }}</div>
		<div class="f_i_i">{{ form.contact_user }}</div>
		
		<div class="f_i_e">{{ form.industry.errors }}</div>
		<div class="f_i_t">{{ form.industry.label_tag }}</div>
		<div class="f_i_i">{{ form.industry }}</div>
		<div class="f_i_e">{{ form.website.errors }}</div>
		<div class="f_i_t">{{ form.website.label_tag }}</div>
		<div class="f_i_i">{{ form.website }}</div>
		</div>
		<div style="width:45%;margin-left:5%;float:left;">
		<fieldset style="width:385px;float:left;">
			<legend style="margin-left:140px;">{% trans "Statistics" %}</legend>
			<div class="f_i_e_2cols">{{ form.employee.errors }}</div>
			<div class="f_i_t_2cols">{{ form.employee.label_tag }}</div>
			<div class="f_i_i_2cols">{{ form.employee }}</div>
			<div class="f_i_e_2cols">{{ form.budget.errors }}</div>
			<div class="f_i_t_2cols">{{ form.budget.label_tag }}</div>
			<div class="f_i_i_2cols">{{ form.budget }}</div>
			<div class="f_i_e_2cols">{{ form.stage.errors }}</div>
			<div class="f_i_t_2cols">{{ form.stage.label_tag }}</div>
			<div class="f_i_i_2cols">{{ form.stage }}</div>
			<div class="f_i_e_2cols">{{ form.main_os.errors }}</div>
			<div class="f_i_t_2cols">{{ form.main_os.label_tag }}</div>
			<div class="f_i_i_2cols">{{ form.main_os }}</div>
		</fieldset>
		</div>
		
		<fieldset id="company_services" style="float:left;width:900px;">
			<legend style="margin-left:385px;">{% trans "Company Services" %}</legend>	
			<div class="f_i_e">{{ form.sub_aws_services.errors }}</div>
			<div class="f_i_t" style="width:100%">{{ form.sub_aws_services.label_tag }}</div>
			<div class="f_i_i" style="width:100%;padding-left:0px;">{{ form.sub_aws_services }}</div>
		</fieldset> 
	</fieldset>  
<table style="width: 100%">
	
                        <tr><td>&nbsp;</td></tr>
                        <tr>
	                        <td>
				</td>
			</tr>
</table>
        <div class="form_block" style="float:right;height:50px;">
            <input type="submit" value="Update" /><input type="button" class="button" value="Cancel" onclick="window.location='{% url "company" %}';"/>
        </div>
</form>

{% endblock %}

base/templates/profiles/email.html
{% extends "sd_admin/base.html" %}

{% load i18n %}
{% load uni_form_tags %}

{% block head_title %}{% trans "Email Address" %}{% endblock %}

{% block nav_title %}Show: Email Address{% endblock nav_title %}
<script type="text/javsacript">
$(document).ready(function){
    init_uniform();
});
</script>
{% block content %}
    <h1>{% trans "Account" %}</h1>
    
    <h2>{% trans "Email Addresses" %}</h2>
    
    {% if user.emailaddress_set.all %}
        <table class="email_list">
            {% for emailaddress in user.emailaddress_set.all %}
                <tr>
                    <td>{% if emailaddress.primary %}<b>{{ emailaddress.email }}</b>{% else %}{{ emailaddress.email }}{% endif %}</td>
                    {% if emailaddress.verified %}
                        <td>
                            <span class="verified">{% trans "verified" %}</span>
                            {% if emailaddress.primary %}
                                - <span class="primary">{% trans "primary" %}</span>
                            {% else %}
                                <form style="display: none;" id="primary_{{ forloop.counter }}" method="post" action="">{% csrf_token %}
                                    <input type="hidden" name="email" value="{{ emailaddress.email }}"/>
                                    <input type="hidden" name="action" value="primary"/>
                                </form>
                                -
                                <a href="#" onclick="$('#primary_{{ forloop.counter }}').submit();">{% trans "make primary" %}</a>
                            {% endif %}
                        </td>
                    {% else %}
                        <td>
                            <span class="unverified">{% trans "unverified" %}</span>
                            <form style="display: none;" id="send_{{ forloop.counter }}" method="post" action="">{% csrf_token %}
                                <input type="hidden" name="email" value="{{ emailaddress.email }}"/>
                                <input type="hidden" name="action" value="send"/>
                            </form>
                            -
                            <a href="#" onclick="$('#send_{{ forloop.counter }}').submit();">{% trans "re-send verification email" %}</a>
                        </td>
                    {% endif %}
                    <td>
                        {% if emailaddress.primary %}
                        {% else %}
                            <form style="display: none;" id="remove_{{ forloop.counter }}" method="post" action="">{% csrf_token %}
                                <input type="hidden" name="email" value="{{ emailaddress.email }}"/>
                                <input type="hidden" name="action" value="remove"/>
                            </form>
                            <a class="remove" href="#" onclick="$('#remove_{{ forloop.counter }}').submit()">{% trans "remove" %}</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %} {# no user.emailaddress_set.all #}
        <p><span class="warning">{% trans "None" %}</span>. {% trans "You should really add one so you can receive notifications, reset your password if you forget it, etc." %}</p>
    {% endif %}
    
    <h3>{% trans "Add Email Address" %}</h3>
    
    <form method="post" action="" class="uniForm">{% csrf_token %}
        <fieldset class="inlineLabels">
            {{ add_email_form|as_uni_form }}
             <div class = "form_block">
                 <input type="hidden" name="action" value="add"/>
                 <input type="submit" value="{% trans "add" %}"/>
            </div>
        </fieldset>
    </form>


{% endblock %}

base/templates/profiles/profile_edit_facebox.html
{% load i18n %}

<h1>{% trans "Edit Profile" %}</h1>

{% include "profiles/profile_form.html" %}